# Generated by Django 5.1.3 on 2024-11-22 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(help_text='место, в котором выполняется привычка', max_length=100, verbose_name='место')),
                ('time', models.TimeField(help_text='время, когда выполняется привычка', verbose_name='время')),
                ('action', models.CharField(help_text='действие, которое выполняется', max_length=100, verbose_name='действие')),
                ('is_pleasant', models.BooleanField(default=False, verbose_name='приятная привычка')),
                ('sign_of_pleasant_habit', models.BooleanField(default=False, verbose_name='признак приятной привычки')),
                ('frequency', models.PositiveSmallIntegerField(default=1, verbose_name='периодичность привычки, в днях')),
                ('reward', models.CharField(blank=True, max_length=255, null=True, verbose_name='вознаграждение')),
                ('complete_time', models.DurationField(verbose_name='Время на выполнение привычки')),
                ('is_public', models.BooleanField(default=False, verbose_name='Публичная привычка')),
                ('related_habits', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habits', verbose_name='связанная привычка')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='создатель привычки')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
            },
        ),
    ]
