# Generated by Django 5.1.3 on 2024-11-23 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_remove_habits_sign_of_pleasant_habit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='habits',
            old_name='related_habits',
            new_name='related_habit',
        ),
    ]
